CREATE SCHEMA IF NOT EXISTS `premise_user` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `premise_data` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `premise_system` DEFAULT CHARACTER SET utf8;