CREATE SCHEMA IF NOT EXISTS `announcement_security` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `announcement_service` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `announcement_company` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `announcement_user_10m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `announcement_user_20m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `announcement_main` DEFAULT CHARACTER SET utf8;