<?php

// @formatter:off
// ----
// private/custom.php
// ----

define("NEED_SEND_ACTIVE_MEMBER_PUSH"			, ${NEED_SEND_ACTIVE_MEMBER_PUSH});
define("NEED_SEND_JOIN_REQUEST_PUSH"			, ${NEED_SEND_JOIN_REQUEST_PUSH});
define("NEED_SEND_GUEST_MEMBER_PUSH"			, ${NEED_SEND_GUEST_MEMBER_PUSH});
define("STAT_GRAPH_IMAGE_CONVERSATION_RECEIVER"		, "${STAT_GRAPH_IMAGE_CONVERSATION_RECEIVER}");