-- DROP DATABASE `pivot_auth_story_2021`;
-- DROP DATABASE `pivot_auth_story_2022`;
-- DROP DATABASE `pivot_security_story_2021`;
-- DROP DATABASE `pivot_security_story_2022`;
-- DROP DATABASE `pivot_service`;
-- DROP DATABASE `pivot_voip_token_uniq`;
-- DROP DATABASE `pivot_device`;
-- DROP DATABASE `pivot_invite`;