CREATE SCHEMA IF NOT EXISTS `partner_data` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `partner_invite_link` DEFAULT CHARACTER SET utf8;

/* REDESIGN */
CREATE SCHEMA IF NOT EXISTS `pivot_company_10m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2021` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2022` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2023` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2024` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2025` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2026` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2027` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_auth_2028` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_system` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_data` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_phone` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2021` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2022` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2023` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2024` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2025` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2026` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2027` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_history_logs_2028` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_user_10m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_user_20m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_sms_service` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2021` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2022` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2023` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2024` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2025` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2026` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2027` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_file_2028` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_company_service` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_userbot` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_rating_10m` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_rating_20m` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `pivot_system`.`company_count_by_day` (
	`day_at` INT NOT NULL,
	`count` BIGINT(20) NOT NULL,
	PRIMARY KEY (`day_at`))
	ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `pivot_system`.`action_count_by_day` (
	`day_at` INT NOT NULL,
	`count` BIGINT(20) NOT NULL,
	PRIMARY KEY (`day_at`))
	ENGINE = InnoDB;
CREATE TABLE IF NOT EXISTS `pivot_system`.`online_user_by_day_all` (
	`day_at` INT NOT NULL,
	`user_id` BIGINT(20) NOT NULL,
	PRIMARY KEY (`day_at`, `user_id`))
	ENGINE = InnoDB;

CREATE SCHEMA IF NOT EXISTS `pivot_business` DEFAULT CHARACTER SET utf8;
CREATE SCHEMA IF NOT EXISTS `pivot_attribution` DEFAULT CHARACTER SET utf8;