USE `pivot_auth_2027`;

DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_1`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_2`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_3`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_4`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_5`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_6`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_7`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_8`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_9`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_10`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_11`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_mail_list_12`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_1`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_2`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_3`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_4`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_5`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_6`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_7`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_8`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_9`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_10`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_11`;
DROP TABLE IF EXISTS `pivot_auth_2027`.`auth_sso_list_12`;
